[
    CustomGetOwnPropertySlot,
    CustomPutFunction,
] interface NodeProxy {
    //void    hello( );
    [Custom] readonly attribute boolean     flag; //use Custom to genereate getOwnPropertySlot
};
